export const dataClass = [
    {
        "EMPLID": "100088989",
        "STRM": "2222",
        "CLASS_NBR": "1009",
        "CLASS_MTG_NBR": "1",
        "DESCR": "Desempeño Universitario",
        "CRSE_ID": "001002",
        "SUBJECT": "HUM",
        "CATALOG_NBR": "2",
        "SSR_COMPONENT": "PRA",
        "FECH_INI": "2021-05-05",
        "FECH_FIN": "2021-07-18",
        "MEETING_TIME_START": "19:30:00",
        "MEETING_TIME_END": "20:10:00",
        "MON": "N",
        "TUES": "N",
        "WED": "Y",
        "THURS": "N",
        "FRI": "N",
        "SAT": "N",
        "SUN": "N",
        "FACILITY_ID": "LN01_AULA2",
        "CRSE_OFFER_NBR": "1",
        "SESSION_CODE": "1",
        "CLASS_SECTION": "1F",
        "INSTITUTION": "PREGR",
        "INSTRUCTOR_ID": "3-3",
        "STDNT_ENRL_STATUS": "E",
        "HOLIDAY_SCHEDULE": "UCS_21",
        "DOCENTE": "CORNEJO PEÑA,RURITZA MILAGROS",
        "LOCAL": "Campus Lima Norte 1",
        "ACAD_CAREER": "UGRD",
        "DESCR_FACILITY": "AULA 2 LIMA NORTE",
        "CLASS_NBR2": "0"
      },
      {
        "EMPLID": "100088989",
        "STRM": "2222",
        "CLASS_NBR": "1763",
        "CLASS_MTG_NBR": "1",
        "DESCR": "Lengua y Comunicación",
        "CRSE_ID": "810329",
        "SUBJECT": "HUM",
        "CATALOG_NBR": "103",
        "SSR_COMPONENT": "TEO",
        "FECH_INI": "2021-05-05",
        "FECH_FIN": "2021-07-18",
        "MEETING_TIME_START": "15:00:00",
        "MEETING_TIME_END": "19:30:00",
        "MON": "N",
        "TUES": "N",
        "WED": "Y",
        "THURS": "N",
        "FRI": "N",
        "SAT": "N",
        "SUN": "N",
        "FACILITY_ID": "LN01_A1CO",
        "CRSE_OFFER_NBR": "1",
        "SESSION_CODE": "1",
        "CLASS_SECTION": "1H",
        "INSTITUTION": "PREGR",
        "INSTRUCTOR_ID": "3-3",
        "STDNT_ENRL_STATUS": "E",
        "HOLIDAY_SCHEDULE": "UCS_21",
        "DOCENTE": "VERA CHAPARRO,VANESSA GIANINA",
        "LOCAL": "Campus Lima Norte 1",
        "ACAD_CAREER": "UGRD",
        "DESCR_FACILITY": "AULA 1CO LIMA NORTE",
        "CLASS_NBR2": "1763"
      }
];