export const dataClass = [
  {
    "EMPLID": "100022216", 
    "STRM": "0941", 
    "CLASS_NBR": "1014", 
    "CLASS_MTG_NBR": "2", 
    "DESCR": "Revisi\u00f3n de la Literatura", 
    "CRSE_ID": "667813", 
    "SUBJECT": "ORT", 
    "CATALOG_NBR": "20", 
    "SSR_COMPONENT": "PRA", 
    "FECH_INI": "2021-08-20", 
    "FECH_FIN": "2021-11-19", 
    "MEETING_TIME_START": "23:17:00", 
    "MEETING_TIME_END": "23:22:00", 
    "MON": "N", 
    "TUES": "N", 
    "WED": "N", 
    "THURS": "N", 
    "FRI": "Y", 
    "SAT": "N", 
    "SUN": "N", 
    "FACILITY_ID": "UP01_704CO", 
    "CRSE_OFFER_NBR": "1", 
    "SESSION_CODE": "1", 
    "CLASS_SECTION": "4A", 
    "INSTITUTION": "ESPEC", 
    "INSTRUCTOR_ID": "5-5", 
    "STDNT_ENRL_STATUS": "E", 
    "HOLIDAY_SCHEDULE": "UCS_21", 
    "DOCENTE": "CABALLERO PURIZAGA,PAOLA JANETT", 
    "LOCAL": "Cantuarias", 
    "ACAD_CAREER": "ESPE", 
    "DESCR_FACILITY": "AULA 704_CO", 
    "CLASS_NBR2": "0"
  },

  {
    "EMPLID": "100022216",
    "STRM": "0941",
    "CLASS_NBR": "1022",
    "CLASS_MTG_NBR": "2",
    "DESCR": "Cl\u00ednica de Ortodoncia IV",
    "CRSE_ID": "667814",
    "SUBJECT": "ORT",
    "CATALOG_NBR": "21",
    "SSR_COMPONENT": "PRA",
    "FECH_INI": "2021-08-20",
    "FECH_FIN": "2021-11-19",
    "MEETING_TIME_START": "23:33:00",
    "MEETING_TIME_END": "23:35:00",
    "MON": "N",
    "TUES": "N",
    "WED": "N",
    "THURS": "N",
    "FRI": "Y",
    "SAT": "N",
    "SUN": "N",
    "FACILITY_ID": "UB02_CLI5A",
    "CRSE_OFFER_NBR": "1",
    "SESSION_CODE": "1",
    "CLASS_SECTION": "4A2",
    "INSTITUTION": "ESPEC",
    "INSTRUCTOR_ID": "5-5",
    "STDNT_ENRL_STATUS": "E",
    "HOLIDAY_SCHEDULE": "UCS_21",
    "DOCENTE": "HUASCO HUARCAYA,NELLY ERLINDA",
    "LOCAL": "Ricardo Palma",
    "ACAD_CAREER": "ESPE",
    "DESCR_FACILITY": "CLINICA 5A",
    "CLASS_NBR2": "1020"
  }, {
    "EMPLID": "100022216",
    "STRM": "0941",
    "CLASS_NBR": "1020",
    "CLASS_MTG_NBR": "2",
    "DESCR": "Cl\u00ednica de Ortodoncia IV",
    "CRSE_ID": "667814",
    "SUBJECT": "ORT",
    "CATALOG_NBR": "21",
    "SSR_COMPONENT": "TEO",
    "FECH_INI": "2021-08-20",
    "FECH_FIN": "2021-11-19",
    "MEETING_TIME_START": "23:22:00",
    "MEETING_TIME_END": "23:27:00",
    "MON": "N",
    "TUES": "N",
    "WED": "N",
    "THURS": "N",
    "FRI": "Y",
    "SAT": "N",
    "SUN": "N",
    "FACILITY_ID": "UP01_704CO",
    "CRSE_OFFER_NBR": "1",
    "SESSION_CODE": "1",
    "CLASS_SECTION": "4A",
    "INSTITUTION": "ESPEC",
    "INSTRUCTOR_ID": "5-5",
    "STDNT_ENRL_STATUS": "E",
    "HOLIDAY_SCHEDULE": "UCS_21",
    "DOCENTE": "WATANABE KANNO,GUSTAVO ADOLFO",
    "LOCAL": "Cantuarias",
    "ACAD_CAREER": "ESPE",
    "DESCR_FACILITY": "AULA 704_CO",
    "CLASS_NBR2": "1020"
  },
  {
    "EMPLID": "100022216",
    "STRM": "0941",
    "CLASS_NBR": "1020",
    "CLASS_MTG_NBR": "2",
    "DESCR": "Cl\u00ednica de Ortodoncia IV",
    "CRSE_ID": "667814",
    "SUBJECT": "ORT",
    "CATALOG_NBR": "21",
    "SSR_COMPONENT": "TEO",
    "FECH_INI": "2021-08-20",
    "FECH_FIN": "2021-11-19",
    "MEETING_TIME_START": "23:40:00",
    "MEETING_TIME_END": "23:55:00",
    "MON": "N",
    "TUES": "N",
    "WED": "N",
    "THURS": "N",
    "FRI": "Y",
    "SAT": "N",
    "SUN": "N",
    "FACILITY_ID": "UP01_704CO",
    "CRSE_OFFER_NBR": "1",
    "SESSION_CODE": "1",
    "CLASS_SECTION": "4A",
    "INSTITUTION": "ESPEC",
    "INSTRUCTOR_ID": "5-5",
    "STDNT_ENRL_STATUS": "E",
    "HOLIDAY_SCHEDULE": "UCS_21",
    "DOCENTE": "WATANABE KANNO,GUSTAVO ADOLFO",
    "LOCAL": "Cantuarias",
    "ACAD_CAREER": "ESPE",
    "DESCR_FACILITY": "AULA 704_CO",
    "CLASS_NBR2": "1020"
  }
];