export const dataClass = [
    {
        ACAD_CAREER: "UGRD",
        CATALOG_NBR: "307",
        CLASS_MTG_NBR: "1",
        CLASS_NBR: "4129",
        CLASS_NBR2: "4128",
        CLASS_SECTION: "3F1",
        CRSE_ID: "001362",
        CRSE_OFFER_NBR: "1",
        DESCR: "Economía",
        DESCR_FACILITY: "AULA A-305 ATE",
        DESC_COMPONE: "Prácticas",
        DOCENTE: "-",
        EMPLID: "100088989",
        FACILITY_ID: "ATE01_305",
        FECH_FIN: "2021-12-05",
        FECH_INI: "2021-08-27",
        FRI: "Y",
        HOLIDAY_SCHEDULE: "UCS_21",
        INSTITUTION: "PREGR",
        INSTRUCTOR_ID: "5-5",
        LOCAL: "Campus Ate 1",
        MEETING_TIME_END: "16:00:00",
        MEETING_TIME_START: "14:26:00",
        MON: "N",
        SAT: "N",
        SESSION_CODE: "1",
        SSR_COMPONENT: "PRA",
        STDNT_ENRL_STATUS: "E",
        STRM: "2223",
        SUBJECT: "EN",
        SUN: "N",
        THURS: "N",
        TUES: "N"

    },
    {
        ACAD_CAREER: "UGRD",
        CATALOG_NBR: "203",
        CLASS_MTG_NBR: "1",
        CLASS_NBR: "6501",
        CLASS_NBR2: "6500",
        CLASS_SECTION: "2G1",
        CRSE_ID: "810345",
        CRSE_OFFER_NBR: "1",
        DESCR: "Lengua y comunicación 2",
        DESCR_FACILITY: "AULA B-104 ATE",
        DESC_COMPONE: "Prácticas",
        DOCENTE: "?AHUIS ARTETA,ROMMEL GERMAN",
        EMPLID: "100088989",
        FACILITY_ID: "ATE01_104",
        FECH_FIN: "2021-12-05",
        FECH_INI: "2021-08-27",
        FRI: "Y",
        HOLIDAY_SCHEDULE: "UCS_21",
        INSTITUTION: "PREGR",
        INSTRUCTOR_ID: "5-5",
        LOCAL: "Campus Ate 1",
        MEETING_TIME_END: "14:25:00",
        MEETING_TIME_START: "12:24:00",
        MON: "N",
        SAT: "N",
        SESSION_CODE: "1",
        SSR_COMPONENT: "PRA",
        STDNT_ENRL_STATUS: "E",
        STRM: "2223",
        SUBJECT: "HUM",
        SUN: "N",
        THURS: "N",
        TUES: "N"
    }
];