export const notice = [
    {
        imgPath: 'https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/tutorial-cambio-contrasena.png',
        title: 'CONFIGURA TU CORREO CIENTÍFICA  ',
        new: true,
        content: `📨 Desde el lunes 14 de febrero, tú mismo podrás cambiar o reestablecer la contraseña de tu correo Científica de un modo más rápido y seguro. Solo debes configurar tu cuenta. Sigue los pasos <a target="_blank" href="https://docs.cientifica.edu.pe/ux/CORREO%20CIENTIFICA.png">aquí</a><br>
        Recuerda: Esto es requisito para tu correo institucional de Microsoft 365.<br> Asegúrate de realizarlo para no tener inconvenientes de acceso. `,
        filtroInst: ['ALL'],
        filtroCarr: ['ALL'],
        useCSV: false,
        useCSV2: false,
        useCSV3: false,
        useCSV4: false,
        useCSV5: false,
        useCSV6: false,
        useCSV7: false,
        useCSV8: false,
        expand: true,
        full: true,
    },
    {
        imgPath: 'https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/actividades-embleabilidad-webinars-febrero.png',
        title: 'Webinars de Empleabilidad - Febrero',
        new: true,
        content: `Te invitamos a participar de los webinars de Empleabilidad del mes de <a target="_blank" href="https://drive.google.com/file/d/12hevnapcHtrAoQ6iNCeXj4TDRCZhpYFW/view">febrero</a>`,
        filtroInst: ['PREGR', 'CPE','PSTGR'],
        filtroCarr: ['ALL'],
        useCSV: false,
        useCSV2: false,
        useCSV3: false,
        useCSV4: false,
        useCSV5: false,
        useCSV6: false,
        useCSV7: false,
        useCSV8: false,
        expand: true,
        full: true,
    },
    {
        imgPath: 'https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/ruta-pasos-ppp-febrero.png',
        title: 'Rutas y pasos para la validación de Prácticas preprofesionales',
        new: true,
        content: `Conoce todo lo necesario para Validar tus prácticas preprofesionales y cumplir con este requisito de egreso.<br><a target="_blank" href="https://us02web.zoom.us/meeting/register/tZMsdumtqTooGdDQ06IyCZku2_FRlHXODr9D">Ingresa Aquí</a>`,
        filtroInst: ['PREGR', 'CPE'],
        filtroCarr: ['ALL'],
        useCSV: false,
        useCSV2: false,
        useCSV3: false,
        useCSV4: false,
        useCSV5: false,
        useCSV6: false,
        useCSV7: false,
        useCSV8: false,
        expand: true,
        full: true,
    },
    {
        imgPath: 'https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/calendario-matricula-posgrado-2022.jpg',
        title: 'CALENDARIO DE MATRÍCULA POSGRADO FEBRERO 2022',
        new: false,
        content: `Para conocer el calendario de matrícula y nuevos inicios, revisa el siguiente <a target="_self" href="assets/pdfjs/CALENDARIO_2022.pdf" download>link.</a>`,
        filtroInst: [],
        filtroCarr: [],
        useCSV: true,
        useCSV2: false,
        useCSV3: false,
        useCSV4: false,
        useCSV5: false,
        useCSV6: false,
        useCSV7: false,
        useCSV8: false,
        expand: true,
        full: true,
    },
    {
        imgPath: 'https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/matricula-externado-2022.jpg',
        title: 'MATRÍCULA EXTERNADO DE MEDICINA HUMANA 2022',
        new: false,
        content: `¡Hola! Pronto comenzará la Matrícula de Externado de Medicina Humana 2022. Te invitamos a revisar el siguiente <a href="https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/documentos/matricula-ecterno-medicina-2022.pdf" target="_blank">link</a> con toda la información necesaria.`,
        filtroInst: [],
        filtroCarr: [],
        useCSV: false,
        useCSV2: false,
        useCSV3: false,
        useCSV4: false,
        useCSV5: false,
        useCSV6: false,
        useCSV7: false,
        useCSV8: true,
        expand: true,
        full: true,
    },
    {
        imgPath: 'https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/270122-admision.jpg',
        title: 'REGULARIZA TUS DOCUMENTOS DE ADMISIÓN',
        new: false,
        content: `¡Hola! Si aún tienes documentos por regularizar ingresa <a target="_blank" href="https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/documentos/radmision-2022-1-pregrado.pdf">aquí</a> y conoce los pasos que debes realizar.<br>
        Fecha límite de entrega: 15 de febrero de 2022<br>
        (*) Omitir este mensaje en caso hayas entregado la documentación.`,
        filtroInst: [],
        filtroCarr: [],
        useCSV: false,
        useCSV2: false,
        useCSV3: false,
        useCSV4: true,
        useCSV5: false,
        useCSV6: false,
        useCSV7: false,
        useCSV8: false,
        expand: true,
        full: true,
    },
    {
        imgPath: 'https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/270122-admision.jpg',
        title: 'REGULARIZA TUS DOCUMENTOS DE ADMISIÓN',
        new: false,
        content: `¡Hola! Si aún tienes documentos por regularizar ingresa <a target="_blank" href="https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/documentos/radmision-2022-1-cpe.pdf">aquí</a> y conoce los pasos que debes realizar.<br>
        Fecha límite de entrega: 15 de febrero de 2022<br>
        (*) Omitir este mensaje en caso hayas entregado la documentación.`,
        filtroInst: [],
        filtroCarr: [],
        useCSV: false,
        useCSV2: false,
        useCSV3: false,
        useCSV4: false,
        useCSV5: true,
        useCSV6: false,
        useCSV7: false,
        useCSV8: false,
        expand: true,
        full: true,
    }
    // {
    //     imgPath: 'https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/bbva-banner.jpg',
    //     title: 'El BBVA se une a la familia científica como un nuevo medio de Pago',
    //     new: false,
    //     content: `Hola te invitamos a revisar esta importante información en el siguiente <a target="_blank" href="https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/documentos/comunicado-bbva.pdf">link</a>`,
    //     filtroInst: ['ALL'],
    //     filtroCarr: ['ALL'],
    //     useCSV: false,
    //     useCSV2: false,
    //     expand: true,
    //     full: true,
    // },
    // {
    //     imgPath: 'https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/Imagen%20charla%2008.11.JPG',
    //     title: 'Charla: El arte de aceptarse',
    //     new: false,
    //     content: `Participa en un maravilloso encuentro contigo mismo y aprende con nosotros a identificar y potenciar tus características personales para vivir de una manera integrada y plena. ¡Te esperamos!. Inscríbete <a target="_blank" href="https://forms.gle/L8Sq9tHADHi4wSt49">aquí</a></p>`,
    //     filtroInst: ['PREGR'],
    //     filtroCarr: ['PFMEH'],
    //     useCSV: false,
    //     useCSV2: false,
    //     expand: true,
    //     full: true,
    // },
//     {
//         imgPath: 'https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/TalentShow.png',
//         title: 'Evento Semana de la medicina Científica',
//         new: true,
//         content: `¡Hola, ven a celebrar la semana de la medicina con tus compañeros, con tus docentes y con nosotros!
// <p class="m-0">Muéstranos tu talento artístico en un TikTok en una noche de talentos moderna. Vamos a divertirnos jugando a ser médicos con los simuladores y pondremos a prueba nuestros conocimientos en una trivia académica. ¡Te esperamos!</p>
// <p class="m-0">Bases del concurso en el siguiente enlace: <a target="_blank" href="https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/documentos/pregrado/medicina/evento-semana-medicina-bases.pf">Link de las bases</a></p>
// <p class="m-0">Inscribe a tu equipo en el siguiente enlace: <a target="_blank" href="https://forms.office.com/Pages/ResponsePage.aspx?id=EM3epWWRNkamTHlYAEIV-qsRmH0SHCNOl5DlSkBK9RNUNVZQUjRGRFlNNlpUTDc3VTJTRVZNWlhQUi4u&wdLOR=cDAC192C5-C5EB-4818-8EF8-65CDB0A5FCEC">Link de inscripción</a></p>`,
//         filtroInst: ['PREGR'],
//         filtroCarr: ['PFMEH'],
//         useCSV: false,
//         useCSV2: false,
//         expand: true,
//         full: true,
//     },
//     {
//         imgPath: 'https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/Imagen%20Conversatorio%20Medicina%20VGU%2021%202.jpg',
//         title: 'Conversatorio: Historias de éxito, ¿por qué amo la Medicina Humana? ',
//         new: true,
//         content: `Participa y conoce la historia de Gabriela, una egresada de Medicina Humana en UCSUR, quien al igual que tú, empezó con la misma pasión y ahora construye un mundo mejor. ¡Te esperamos!. Inscríbete aquí: <a target="_blank" href="https://forms.gle/ihqWqn38PzA3YAoB9">https://forms.gle/ihqWqn38PzA3YAoB9</a>`,
//         filtroInst: ['PREGR'],
//         filtroCarr: ['PFMEH'],
//         useCSV: false,
//         useCSV2: false,
//         expand: true,
//         full: true,
//     },
    // {
    //     imgPath: './assets/img/notice_10.png',
    //     title: 'Participa en el Impact Startup Competition',
    //     new: false,
    //     content: `El área de emprendimiento y el comité local están organizando el Impact Startup Competition Ucsur, programa para fomentar emprendimientos que apoyen a los objetivos de desarrollo sostenibles. Se darán horas extracurriculares. <a href="https://sites.google.com/view/iscucsur/inicio">Más info aquí.</a>`,
    //     filtroInst: ['PREGR', 'CPE'],
    //     filtroCarr: ['ALL'],
    //     useCSV: false,
    //     useCSV2: false,
    //     expand: true,
    //     full: true,
    // },
    // {
    //     imgPath: './assets/img/notice_12.jpg',
    //     title: 'COMUNICADO CLASES PRESENCIALES 2022-1',
    //     new: false,
    //     content: `Invocamos a todos nuestros estudiantes a leer este importante comunicado de la Universidad. <a target="_blank" href="https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/Comunicado%20CLASES%20PRESENCIALES%202022%20Vfinal.pdf">Ver comunicado</a>`,
    //     filtroInst: ['ALL'],
    //     filtroCarr: ['ALL'],
    //     useCSV: false,
    //     useCSV2: false,
    //     useCSV3: false,
    //     useCSV4: false,
    //     useCSV5: false,
    //     useCSV6: false,
    //     useCSV7: false,
    //     useCSV8: false,
    //     expand: true,
    //     full: true,
    // }
];