export const notice = [
    {
        imgPath: 'https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/intencion-matricula-2022-1.jpg',
        title: 'INTENCIÓN DE MATRÍCULA 2022-1',
        new: true,
        content: `¡Hola! Muy pronto iniciará la Intención de Matrícula 2022-1. Te invitamos a revisar el siguiente <a target="_blank" href="https://www.cientifica.edu.pe/sites/default/files/2022-01/Comunicado_IM%20CPE_2022-1%20vCX_0.pdf">link</a> con toda la información necesaria.`,
        filtroInst: [],
        filtroCarr: [],
        useCSV: false,
        useCSV2: true,
        useCSV3: false,
        useCSV4: false,
        useCSV5: false,
        useCSV6: false,
        useCSV7: false,
        useCSV8: false,
        expand: true,
        full: true,
    },
    {
        imgPath: 'https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/intencion-matricula-2022-1.jpg',
        title: 'INTENCIÓN DE MATRÍCULA 2022-1',
        new: true,
        content: `¡Hola! Muy pronto iniciará la Intención de Matrícula 2022-1. Te invitamos a revisar el siguiente <a target="_blank" href="https://www.cientifica.edu.pe/sites/default/files/2022-01/Comunicado_IM%20Pregrado_2022-1%20vCX.pdf">link</a> con toda la información necesaria.`,
        filtroInst: [],
        filtroCarr: [],
        useCSV: false,
        useCSV2: false,
        useCSV3: true,
        useCSV4: false,
        useCSV5: false,
        useCSV6: false,
        useCSV7: false,
        useCSV8: false,
        expand: true,
        full: true,
    },
    {
        imgPath: 'https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/sede-ucsur.jpg',
        title: 'COMUNICADO RETORNO SEGURO A CLASES 2022-1',
        new: true,
        content: `Invocamos a todos nuestros estudiantes a leer este importante comunicado de la Universidad. <a target="_blank" href="https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/comunicado-regreso-seguro-clases.pdf">Ver comunicado</a>`,
        filtroInst: ['ALL'],
        filtroCarr: ['ALL'],
        useCSV: false,
        useCSV2: false,
        useCSV3: false,
        useCSV4: false,
        useCSV5: false,
        useCSV6: false,
        useCSV7: false,
        useCSV8: false,
        expand: true,
        full: true,
    },
    {
        // 24/01/22
        imgPath: 'https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/actividades-extracurriculares-2022-0.jpg',
        title: 'Actividades extracurriculares VGU 2022 0',
        new: false,
        content: `¡Ven y participa con nosotros en las Actividades extracurriculares que tenemos para ti este verano!. Fortalece, desarrolla y aprende herramientas que serán un complemento perfecto para tu perfil profesional. Inscríbete vía Portal de estudiante desde el 13 al 16 de enero 2022, ¡te esperamos!. Más info aquí: <a target="_blank" href="https://bit.ly/3q6Eopa">https://bit.ly/3q6Eopa</a>`,
        filtroInst: ['PREGR', 'CPE'],
        filtroCarr: ['ALL'],
        useCSV: false,
        useCSV2: false,
        useCSV3: false,
        useCSV4: false,
        useCSV5: false,
        useCSV6: false,
        useCSV7: false,
        useCSV8: false,
        expand: true,
        full: true,
    },
    {
        imgPath: 'https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/noticia-311221-posgrado.png',
        title: '💻 ACTUALIZACIÓN DEL INGRESO AL AULA VIRTUAL',
        new: false,
        content: `Desde el 27/12/21, podrás ingresar a tus cursos del Aula Virtual de un modo más sencillo. Sigue los siguientes pasos.<br>
                1. Dale clic a <a href="https://aulavirtualposgrado.cientifica.edu.pe/login/index.php" target="_blank" >aulavirtualposgrado.cientifica.edu.pe</a> <br>
                2. Ingresa los datos de tu correo Científica (correo y contraseña) y listo. <br>
                
                Ten en cuenta:  El icono de acceso desde el “Horario” será desactivado. Si olvidaste tus datos del correo Científica, puedes escribir al WhatsApp +51988 576 507`,
        filtroInst: ['PSTGR', 'ESPEC'],
        filtroCarr: ['ALL'],
        useCSV: false,
        useCSV2: false,
        useCSV3: false,
        useCSV4: false,
        useCSV5: false,
        useCSV6: false,
        useCSV7: false,
        useCSV8: false,
        expand: true,
        full: true,
    },
    {
        imgPath: 'https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/noticia-311221-pre.png',
        title: '¡RENOVAMOS NUESTRA AULA VIRTUAL 💻!',
        new: false,
        content: `Ahora podrás ingresar a la nueva Aula Virtual con la tecnología de Canvas. Solo sigue los siguientes pasos.<br>
                1. Dale clic a <a href="https://cientificavirtual.cientifica.edu.pe/login/canvas" target="_blank" >cientificavirtual.cientifica.edu.pe</a> <br>
                2. Ingresa los datos de tu correo Científica (correo y contraseña) y listo. <br>
                
                Ten en cuenta:  El icono de acceso desde el “Horario” será desactivado. Si olvidaste tus datos del correo Científica, puedes escribir al WhatsApp +51988 576 507`,
        filtroInst: ['PREGR', 'CPE'],
        filtroCarr: ['ALL'],
        useCSV: false,
        useCSV2: false,
        useCSV3: false,
        useCSV4: false,
        useCSV5: false,
        useCSV6: false,
        useCSV7: false,
        useCSV8: false,
        expand: true,
        full: true,
    },
    {
        // 24/01/22
        imgPath: 'https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/calendario-matricula-pstg2022.jpg',
        title: 'CALENDARIO DE MATRÍCULA POSGRADO ENERO 2022',
        new: false,
        content: `Para conocer el calendario de matrícula y nuevos inicios, revisa el siguiente <a target="_blank" href="https://www.cientifica.edu.pe/sites/default/files/2021-12/Calendario%20Posgrado_Enero%202022.pdf">Link</a>`,
        filtroInst: [],
        filtroCarr: [],
        useCSV: true,
        useCSV2: false,
        useCSV3: false,
        useCSV4: false,
        useCSV5: false,
        useCSV6: false,
        useCSV7: false,
        useCSV8: false,
        expand: true,
        full: true,
    },
    // {
    //     imgPath: 'https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/bbva-banner.jpg',
    //     title: 'El BBVA se une a la familia científica como un nuevo medio de Pago',
    //     new: false,
    //     content: `Hola te invitamos a revisar esta importante información en el siguiente <a target="_blank" href="https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/documentos/comunicado-bbva.pdf">link</a>`,
    //     filtroInst: ['ALL'],
    //     filtroCarr: ['ALL'],
    //     useCSV: false,
    //     useCSV2: false,
    //     expand: true,
    //     full: true,
    // },
    // {
    //     imgPath: 'https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/Imagen%20charla%2008.11.JPG',
    //     title: 'Charla: El arte de aceptarse',
    //     new: false,
    //     content: `Participa en un maravilloso encuentro contigo mismo y aprende con nosotros a identificar y potenciar tus características personales para vivir de una manera integrada y plena. ¡Te esperamos!. Inscríbete <a target="_blank" href="https://forms.gle/L8Sq9tHADHi4wSt49">aquí</a></p>`,
    //     filtroInst: ['PREGR'],
    //     filtroCarr: ['PFMEH'],
    //     useCSV: false,
    //     useCSV2: false,
    //     expand: true,
    //     full: true,
    // },
//     {
//         imgPath: 'https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/TalentShow.png',
//         title: 'Evento Semana de la medicina Científica',
//         new: true,
//         content: `¡Hola, ven a celebrar la semana de la medicina con tus compañeros, con tus docentes y con nosotros!
// <p class="m-0">Muéstranos tu talento artístico en un TikTok en una noche de talentos moderna. Vamos a divertirnos jugando a ser médicos con los simuladores y pondremos a prueba nuestros conocimientos en una trivia académica. ¡Te esperamos!</p>
// <p class="m-0">Bases del concurso en el siguiente enlace: <a target="_blank" href="https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/documentos/pregrado/medicina/evento-semana-medicina-bases.pf">Link de las bases</a></p>
// <p class="m-0">Inscribe a tu equipo en el siguiente enlace: <a target="_blank" href="https://forms.office.com/Pages/ResponsePage.aspx?id=EM3epWWRNkamTHlYAEIV-qsRmH0SHCNOl5DlSkBK9RNUNVZQUjRGRFlNNlpUTDc3VTJTRVZNWlhQUi4u&wdLOR=cDAC192C5-C5EB-4818-8EF8-65CDB0A5FCEC">Link de inscripción</a></p>`,
//         filtroInst: ['PREGR'],
//         filtroCarr: ['PFMEH'],
//         useCSV: false,
//         useCSV2: false,
//         expand: true,
//         full: true,
//     },
//     {
//         imgPath: 'https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/Imagen%20Conversatorio%20Medicina%20VGU%2021%202.jpg',
//         title: 'Conversatorio: Historias de éxito, ¿por qué amo la Medicina Humana? ',
//         new: true,
//         content: `Participa y conoce la historia de Gabriela, una egresada de Medicina Humana en UCSUR, quien al igual que tú, empezó con la misma pasión y ahora construye un mundo mejor. ¡Te esperamos!. Inscríbete aquí: <a target="_blank" href="https://forms.gle/ihqWqn38PzA3YAoB9">https://forms.gle/ihqWqn38PzA3YAoB9</a>`,
//         filtroInst: ['PREGR'],
//         filtroCarr: ['PFMEH'],
//         useCSV: false,
//         useCSV2: false,
//         expand: true,
//         full: true,
//     },
    // {
    //     imgPath: './assets/img/notice_10.png',
    //     title: 'Participa en el Impact Startup Competition',
    //     new: false,
    //     content: `El área de emprendimiento y el comité local están organizando el Impact Startup Competition Ucsur, programa para fomentar emprendimientos que apoyen a los objetivos de desarrollo sostenibles. Se darán horas extracurriculares. <a href="https://sites.google.com/view/iscucsur/inicio">Más info aquí.</a>`,
    //     filtroInst: ['PREGR', 'CPE'],
    //     filtroCarr: ['ALL'],
    //     useCSV: false,
    //     useCSV2: false,
    //     expand: true,
    //     full: true,
    // },
    // {
    //     imgPath: './assets/img/notice_12.jpg',
    //     title: 'COMUNICADO CLASES PRESENCIALES 2022-1',
    //     new: false,
    //     content: `Invocamos a todos nuestros estudiantes a leer este importante comunicado de la Universidad. <a target="_blank" href="https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/Comunicado%20CLASES%20PRESENCIALES%202022%20Vfinal.pdf">Ver comunicado</a>`,
    //     filtroInst: ['ALL'],
    //     filtroCarr: ['ALL'],
    //     useCSV: false,
    //     useCSV2: false,
    //     useCSV3: false,
    //     useCSV4: false,
    //     useCSV5: false,
    //     useCSV6: false,
    //     useCSV7: false,
    //     useCSV8: false,
    //     expand: true,
    //     full: true,
    // }
];