export const notice = [
    {
        imgPath: 'https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/calendar-031221.jpg',
        title: 'CALENDARIO DE MATRÍCULA POSGRADO DICIEMBRE 2021',
        new: true,
        content: `Para conocer el calendario de matrícula y nuevos inicios, revisa el siguiente <a target="_blank" href="https://www.cientifica.edu.pe/sites/default/files/2021-12/Calendario%20Posgrado_Dic%202021_0.pdf">link</a>.`,
        filtroInst: [],
        filtroCarr: [],
        useCSV: false,
        useCSV2: false,
        useCSV3: false,
        useCSV4: false,
        useCSV5: false,
        useCSV6: false,
        useCSV7: false,
        useCSV8: false,
        useCSV9: true,
        expand: true,
        full: true,
    },
    {
        imgPath: 'https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/intencion-matricula.jpg',
        title: 'INTENCIÓN DE MATRÍCULA VERANO 2022',
        new: false,
        content: `¡Ya inició la Intención de Matrícula Verano 2022!
        Acepta las condiciones académicas y financieras e inicia con el proceso.`,
        filtroInst: [],
        filtroCarr: [],
        useCSV: false,
        useCSV2: true,
        useCSV3: false,
        useCSV4: false,
        useCSV5: false,
        useCSV6: false,
        useCSV7: false,
        useCSV8: false,
        expand: true,
        full: true,
    },
    {
        imgPath: 'https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/intencion-matricula.jpg',
        title: 'INTENCIÓN DE MATRÍCULA VERANO 2022',
        new: false,
        content: `¡Ya inició la Intención de Matrícula Verano 2022!
        Acepta las condiciones académicas y financieras e inicia con el proceso.`,
        filtroInst: [],
        filtroCarr: [],
        useCSV: false,
        useCSV2: false,
        useCSV3: true,
        useCSV4: false,
        useCSV5: false,
        useCSV6: false,
        useCSV7: false,
        useCSV8: false,
        expand: true,
        full: true,
    },
    { // Pregrado - CES
        imgPath: 'https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/encuesta-221121.jpg',
        title: '¡SOMOS TODO OÍDOS!',
        new: false,
        content: `Por favor haz click en el siguiente <a target="_blank" href="https://forms.gle/ji1iNS9DV6Fgptn8A">link</a>.`,
        filtroInst: [],
        filtroCarr: [],
        useCSV: false,
        useCSV2: false,
        useCSV3: false,
        useCSV4: true,
        useCSV5: false,
        useCSV6: false,
        useCSV7: false,
        useCSV8: false,
        expand: true,
        full: true,
    },
    { // Pregrado - BIBLIOTECA
        imgPath: 'https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/encuesta-221121.jpg',
        title: '¡SOMOS TODO OÍDOS!',
        new: false,
        content: `Por favor haz click en el siguiente <a target="_blank" href="https://forms.gle/6zahSStnEtwij9zAA">link</a>.`,
        filtroInst: [],
        filtroCarr: [],
        useCSV: false,
        useCSV2: false,
        useCSV3: false,
        useCSV4: false,
        useCSV5: true,
        useCSV6: false,
        useCSV7: false,
        useCSV8: false,
        expand: true,
        full: true,
    },
    { // Pregrado - MATRICULA
        imgPath: 'https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/encuesta-221121.jpg',
        title: '¡SOMOS TODO OÍDOS!',
        new: false,
        content: `Por favor haz click en el siguiente <a target="_blank" href="https://forms.gle/FuiiN2DLHnYHBPnH8">link</a>.`,
        filtroInst: [],
        filtroCarr: [],
        useCSV: false,
        useCSV2: false,
        useCSV3: false,
        useCSV4: false,
        useCSV5: false,
        useCSV6: true,
        useCSV7: false,
        useCSV8: false,
        expand: true,
        full: true,
    },
    { // Posgrado - CES
        imgPath: 'https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/encuesta-221121.jpg',
        title: '¡SOMOS TODO OÍDOS!',
        new: false,
        content: `Por favor haz click en el siguiente <a target="_blank" href="https://forms.gle/StqUZ9AUbi5Qwj4i8">link</a>.`,
        filtroInst: [],
        filtroCarr: [],
        useCSV: false,
        useCSV2: false,
        useCSV3: false,
        useCSV4: false,
        useCSV5: false,
        useCSV6: false,
        useCSV7: true,
        useCSV8: false,
        expand: true,
        full: true,
    },
    { // Posgrado - Matricula
        imgPath: 'https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/encuesta-221121.jpg',
        title: '¡SOMOS TODO OÍDOS!',
        new: false,
        content: `Por favor haz click en el siguiente <a target="_blank" href="https://forms.gle/X8sZJbYh6pfsiUNXA">link</a>.`,
        filtroInst: [],
        filtroCarr: [],
        useCSV: false,
        useCSV2: false,
        useCSV3: false,
        useCSV4: false,
        useCSV5: false,
        useCSV6: false,
        useCSV7: false,
        useCSV8: true,
        expand: true,
        full: true,
    },
    {
        imgPath: 'https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/Arte%20Encuesta_CPE-M2_Modificado.jpg',
        title: 'Encuesta de Evaluación del Desempeño docente en Clase 2021-2 – Módulo 2',
        new: false,
        content: `Estimado estudiante, te invitamos a ser parte de la evaluación de tus docentes completando la <a href="https://sedd.cientifica.edu.pe/login/ingresar" target="_blank">Encuesta de Evaluación del Desempeño Docente en clase 2021-2 del Módulo 2 </a>, mediante la cual recogeremos tus apreciaciones con respecto a la labor que realizan. Recuerda que esta encuesta es confidencial y anónima. Tu participación en este proceso es importante, por ello apelamos al compromiso con tu educación y te pedimos realizar esta evaluación con total honestidad y conciencia, pues los resultados nos permitirán asegurar la calidad de tus cursos y docentes. ¡Contamos contigo!`,
        filtroInst: [],
        filtroCarr: [],
        useCSV: true,
        useCSV2: false,
        useCSV3: false,
        useCSV4: false,
        useCSV5: false,
        useCSV6: false,
        useCSV7: false,
        useCSV8: false,
        expand: false,
        full: false,
    },
    // {
    //     imgPath: 'https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/bbva-banner.jpg',
    //     title: 'El BBVA se une a la familia científica como un nuevo medio de Pago',
    //     new: false,
    //     content: `Hola te invitamos a revisar esta importante información en el siguiente <a target="_blank" href="https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/documentos/comunicado-bbva.pdf">link</a>`,
    //     filtroInst: ['ALL'],
    //     filtroCarr: ['ALL'],
    //     useCSV: false,
    //     useCSV2: false,
    //     expand: true,
    //     full: true,
    // },
    // {
    //     imgPath: 'https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/Imagen%20charla%2008.11.JPG',
    //     title: 'Charla: El arte de aceptarse',
    //     new: false,
    //     content: `Participa en un maravilloso encuentro contigo mismo y aprende con nosotros a identificar y potenciar tus características personales para vivir de una manera integrada y plena. ¡Te esperamos!. Inscríbete <a target="_blank" href="https://forms.gle/L8Sq9tHADHi4wSt49">aquí</a></p>`,
    //     filtroInst: ['PREGR'],
    //     filtroCarr: ['PFMEH'],
    //     useCSV: false,
    //     useCSV2: false,
    //     expand: true,
    //     full: true,
    // },
//     {
//         imgPath: 'https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/TalentShow.png',
//         title: 'Evento Semana de la medicina Científica',
//         new: true,
//         content: `¡Hola, ven a celebrar la semana de la medicina con tus compañeros, con tus docentes y con nosotros!
// <p class="m-0">Muéstranos tu talento artístico en un TikTok en una noche de talentos moderna. Vamos a divertirnos jugando a ser médicos con los simuladores y pondremos a prueba nuestros conocimientos en una trivia académica. ¡Te esperamos!</p>
// <p class="m-0">Bases del concurso en el siguiente enlace: <a target="_blank" href="https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/documentos/pregrado/medicina/evento-semana-medicina-bases.pf">Link de las bases</a></p>
// <p class="m-0">Inscribe a tu equipo en el siguiente enlace: <a target="_blank" href="https://forms.office.com/Pages/ResponsePage.aspx?id=EM3epWWRNkamTHlYAEIV-qsRmH0SHCNOl5DlSkBK9RNUNVZQUjRGRFlNNlpUTDc3VTJTRVZNWlhQUi4u&wdLOR=cDAC192C5-C5EB-4818-8EF8-65CDB0A5FCEC">Link de inscripción</a></p>`,
//         filtroInst: ['PREGR'],
//         filtroCarr: ['PFMEH'],
//         useCSV: false,
//         useCSV2: false,
//         expand: true,
//         full: true,
//     },
//     {
//         imgPath: 'https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/Imagen%20Conversatorio%20Medicina%20VGU%2021%202.jpg',
//         title: 'Conversatorio: Historias de éxito, ¿por qué amo la Medicina Humana? ',
//         new: true,
//         content: `Participa y conoce la historia de Gabriela, una egresada de Medicina Humana en UCSUR, quien al igual que tú, empezó con la misma pasión y ahora construye un mundo mejor. ¡Te esperamos!. Inscríbete aquí: <a target="_blank" href="https://forms.gle/ihqWqn38PzA3YAoB9">https://forms.gle/ihqWqn38PzA3YAoB9</a>`,
//         filtroInst: ['PREGR'],
//         filtroCarr: ['PFMEH'],
//         useCSV: false,
//         useCSV2: false,
//         expand: true,
//         full: true,
//     },
    // {
    //     imgPath: './assets/img/notice_10.png',
    //     title: 'Participa en el Impact Startup Competition',
    //     new: false,
    //     content: `El área de emprendimiento y el comité local están organizando el Impact Startup Competition Ucsur, programa para fomentar emprendimientos que apoyen a los objetivos de desarrollo sostenibles. Se darán horas extracurriculares. <a href="https://sites.google.com/view/iscucsur/inicio">Más info aquí.</a>`,
    //     filtroInst: ['PREGR', 'CPE'],
    //     filtroCarr: ['ALL'],
    //     useCSV: false,
    //     useCSV2: false,
    //     expand: true,
    //     full: true,
    // },
    // {
    //     imgPath: './assets/img/notice_12.jpg',
    //     title: 'COMUNICADO CLASES PRESENCIALES 2022-1',
    //     new: false,
    //     content: `Invocamos a todos nuestros estudiantes a leer este importante comunicado de la Universidad. <a target="_blank" href="https://docs.cientifica.edu.pe/miportal_sise/miportal_cientifica/noticias/Comunicado%20CLASES%20PRESENCIALES%202022%20Vfinal.pdf">Ver comunicado</a>`,
    //     filtroInst: ['ALL'],
    //     filtroCarr: ['ALL'],
    //     useCSV: false,
    //     useCSV2: false,
    //     useCSV3: false,
    //     useCSV4: false,
    //     useCSV5: false,
    //     useCSV6: false,
    //     useCSV7: false,
    //     useCSV8: false,
    //     expand: true,
    //     full: true,
    // }
];